Repository boostcampwm-2022/web09-KittyMark, pull requests merged in 2022-12, with the labels that each got.

#110 [be/map] map api 작성
  environment/default.conf
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/auth/auth.guard.ts
  server/src/board/board.entity.ts
  server/src/board/board.repository.ts
  server/src/board/board.service.ts
  server/src/board/board.util.ts
  server/src/board/photo.entity.ts
  server/src/configs/typeorm.config.ts
  server/src/map/dto/get-map.dto.ts
  server/src/map/map.controller.spec.ts
  server/src/map/map.controller.ts
  server/src/map/map.module.ts
  server/src/map/map.service.spec.ts
  server/src/map/map.service.ts
Labels: 💻 BE, 🛠 Feat

#111 [fe/map] Map API 관련 변경사항 및 게시글 관련 재사용 컴포넌트 적용
  client/src/components/BoardItem/BoardHeader/BoardHeader.tsx
  client/src/components/BoardItem/BoardItem.tsx
  client/src/pages/HomePage/HomePage.tsx
  client/src/types/responseData.ts
  client/src/utils/map.ts
Labels: 🎨 FE, 🛠 Feat, 🚧 Refactor

#112 [fe/map] 지도 페이지 API 명세 변경사항 적용 및 검색된 데이터가 없는 경우 처리
  client/src/pages/MapPage/MapPage.tsx
Labels: 🎨 FE, 🐞 BugFix

#114 [fe/new_post_location] 새 게시글 생성 페이지 사용자 위치정보 수집 및 전송
  client/src/apis/api/newPostApi.ts
  client/src/apis/api/reverseGeocoding.ts
  client/src/apis/services/reverseGeocodingService.ts
  client/src/pages/NewPostPage/NewPostPage.tsx
  client/src/setupProxy.js
Labels: 🎨 FE, 🛠 Feat, 🚧 Refactor

#116 [be/like] 좋아요 API작성
  server/src/board/board.controller.ts
  server/src/board/board.entity.ts
  server/src/board/board.module.ts
  server/src/board/board.repository.ts
  server/src/board/board.util.ts
  server/src/board/dto/create-board.dto.ts
  server/src/configs/typeorm.config.ts
  server/src/like/like.entity.ts
  server/src/like/like.module.ts
  server/src/like/like.repository.ts
  server/src/like/like.service.spec.ts
  server/src/like/like.service.ts
  server/src/user/user.entity.ts
Labels: 💻 BE, 🛠 Feat

#117 [fe/follow_page] 팔로우 페이지 refactor 및 react-query 적용
  client/src/apis/api/userApi.ts
  client/src/components/FollowContainer/FollowContainer.tsx
  client/src/components/FollowContainer/FollowContainerStyles.tsx
  client/src/components/FollowUnit/FollowUnit.tsx
  client/src/components/FollowUnit/FollowUnitStyles.tsx
  client/src/components/FollowerContainer/FollowerContainerPage.tsx
  client/src/components/FollowingContainer/FollowingContainer.tsx
  client/src/components/FollowingContainer/FollowingContainerStyles.tsx
  client/src/components/UserInfoContainer/UserInfoContainer.tsx
  client/src/pages/FollowPage/FollowPage.tsx
  client/src/types/responseData.ts
Labels: 🎨 FE, 🛠 Feat, 🚧 Refactor

#118 [be/follow] 팔로우 엔티티 및 팔로우 관련 API 작성
  server/src/app.module.ts
  server/src/comment/comment.entity.ts
  server/src/configs/typeorm.config.ts
  server/src/user/dto/follow.dto.ts
  server/src/user/follow/follow.entity.ts
  server/src/user/follow/follow.module.ts
  server/src/user/follow/follow.repository.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
Labels: 💻 BE, 🛠 Feat

#119 [be/refactor] 이름 중복 체크 api 수정
  client/src/apis/api/loginApi.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/check-name.dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
Labels: 🎨 FE, 💻 BE, 🚧 Refactor

#120 [be/refactor] bug fix
  client/src/apis/api/boardApi.ts
  client/src/apis/api/userApi.ts
  client/src/components/BoardItem/BoardHeader/BoardHeader.tsx
  client/src/components/UserInfoContainer/UserInfoContainer.tsx
  client/src/pages/ModifyPage/ModifyPage.tsx
  server/src/board/board.service.ts
  server/src/user/dto/get-profile-info.dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
Labels: 🎨 FE, 💻 BE, 🐞 BugFix, 🚧 Refactor

#121 [fe/map] 마커 클릭시 해당하는 게시글 보여주는 기능 추가
  client/src/apis/api/reverseGeocoding.ts
  client/src/components/BoardItem/BoardHeader/BoardHeader.tsx
  client/src/components/BoardItem/BoardMenu/BoardMenu.tsx
  client/src/components/BoardItem/BoardMenu/BoardMenuStyles.tsx
  client/src/components/BoardModal/BoardModal.tsx
  client/src/components/BoardModal/BoardModalStyles.tsx
  client/src/pages/MapPage/MapPage.tsx
  client/src/static/closeButton.svg
  client/src/types/responseData.ts
Labels: 🎨 FE, 🛠 Feat, 🚧 Refactor

#122 docs: PR Template 삭제
  .github/pull_request_template.md
Labels: 📄 Docs

#123 [bug/map]현재 위치 조회 api 수정
  client/src/apis/api/reverseGeocoding.ts
  client/src/apis/services/reverseGeocodingService.ts
  client/src/setupProxy.js
  server/src/map/map.controller.ts
  server/src/map/map.module.ts
  server/src/map/map.service.ts
Labels: 🎨 FE, 💻 BE, 🐞 BugFix

#129 [fe/refactor_issue] 댓글, 팔로우 관련 에러 처리 및 로그인 이후 정보 로컬스토리지 저장
  client/src/components/CommentUnit/CommentUnit.tsx
  client/src/components/FollowContainer/FollowContainer.tsx
  client/src/components/FollowUnit/FollowUnit.tsx
  client/src/components/UserInfoContainer/UserInfoContainer.tsx
  client/src/pages/CommentPage/CommentPageStyles.tsx
  client/src/pages/LoginPage/LoginPage.tsx
  client/src/store/userAtom.ts
  client/src/types/responseData.ts
Labels: 🎨 FE, 🐞 BugFix, 🚧 Refactor

#128 [fe/board] 게시글 버그 수정 및 기능 추가
  client/src/components/BoardItem/BoardBody/BoardBody.tsx
  client/src/components/BoardItem/BoardHeader/BoardHeader.tsx
  client/src/components/BoardItem/BoardItem.tsx
  client/src/components/ImageCarousel/ImageCarousel.tsx
  client/src/types/responseData.ts
Labels: 🎨 FE, 🐞 BugFix, 🛠 Feat

#130 [be/refactor] 댓글 리스트 조회, 팔로우/팔로워 리스트 조회 API 수정
  server/src/comment/comment.repository.ts
  server/src/user/follow/follow.repository.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
Labels: 💻 BE, 🚧 Refactor

#132 [fe/detail_page] 유저 게시글 클릭시 상세 페이지 구현
  client/src/App.tsx
  client/src/apis/api/userApi.ts
  client/src/apis/utils/index.ts
  client/src/components/BoardItem/BoardItemStyles.tsx
  client/src/components/FollowContainer/FollowContainer.tsx
  client/src/components/UserPostContainer/UserPostContainer.tsx
  client/src/pages/BoardDetailPage/BoardDetailPage.tsx
  client/src/pages/BoardDetailPage/BoardDetailPageStyles.tsx
  client/src/pages/ModifyUserPage/ModifyUserPage.tsx
  client/src/store/boardDetailAtom.ts
  client/src/store/userProfileAtom.ts
  client/src/types/responseData.ts
  server/src/user/follow/follow.repository.ts
Labels: 🎨 FE, 🛠 Feat, 🚧 Refactor

#134 [fe/like] 좋아요 기능 구현
  client/src/apis/api/boardApi.ts
  client/src/components/BoardItem/BoardBody/BoardBody.tsx
  client/src/components/BoardItem/BoardBody/BoardBodyStyles.tsx
  client/src/components/BoardItem/BoardHeader/BoardHeader.tsx
  client/src/components/BoardItem/BoardHeader/BoardHeaderStyles.tsx
  client/src/components/BoardItem/BoardItem.tsx
  client/src/components/BoardModal/BoardModal.tsx
  client/src/components/BoardModal/BoardModalStyles.tsx
  client/src/components/ImageCarousel/ImageCarousel.tsx
  client/src/components/LikeButton/LikeButton.tsx
  client/src/pages/HomePage/HomePage.tsx
  client/src/pages/HomePage/HomePageStyles.tsx
  client/src/store/boardDetailAtom.ts
  client/src/types/responseData.ts
  server/src/like/like.repository.ts
Labels: 🎨 FE, 💻 BE, 🐞 BugFix, 🛠 Feat, 🚧 Refactor

#135 [fe/code split] react-loadable 을 통한 코드 분할
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/LoadingContainer/LoadingContainer.tsx
  client/src/components/LoadingContainer/LoadingContainerStyles.tsx
  client/src/components/NavBar/NavBar.tsx
  client/src/components/NormalTopBar/NormalTopBar.tsx
  client/src/pages/LoadingPage/LoadingPage.tsx
  client/src/pages/LoginPage/LoginPage.tsx
  client/src/pages/index.tsx
Labels: 🎨 FE, 🛠 Feat, 🚧 Refactor

#137 [be/like enhanced] 게시글 불러오기시 좋아요 여부 확인
  server/src/auth/auth.guard.ts
  server/src/auth/auth.service.ts
  server/src/board/board.controller.ts
  server/src/board/board.repository.ts
  server/src/board/board.service.ts
  server/src/map/map.controller.ts
  server/src/map/map.service.ts
Labels: 💻 BE, 🚧 Refactor

#138 [fe/apply react query] 게시글 및 지도 관련 API React Query 적용
  client/src/apis/api/mapApi.ts
  client/src/components/BoardItem/BoardHeader/BoardHeader.tsx
  client/src/pages/HomePage/HomePage.tsx
  client/src/pages/MapPage/MapPage.tsx
  client/src/types/responseData.ts
  client/src/utils/map/map.ts
  client/src/utils/map/naverMap.ts
Labels: 🎨 FE, 🚧 Refactor

#139 [be/like-enhanced] 좋아요 api 버그수정
  server/src/board/board.entity.ts
  server/src/board/board.repository.ts
  server/src/like/like.repository.ts
  server/src/like/like.service.ts
Labels: 💻 BE, 🐞 BugFix

#142 [fe/map update] 게시글 작성시 위치 설정 기능 추가
  client/public/index.html
  client/src/components/NavBar/NavBarStyles.tsx
  client/src/components/SetLocationModal/SetLocationModal.tsx
  client/src/components/SetLocationModal/SetLocationModalStyles.tsx
  client/src/pages/MapPage/MapPage.tsx
  client/src/pages/MapPage/MapPageStyles.tsx
  client/src/pages/NewPostPage/NewPostPage.tsx
  client/src/pages/NewPostPage/NewPostPageStyles.tsx
  client/src/static/BlueCatSpinner.gif
  client/src/static/footprint.svg
  client/src/static/mapButton.png
  client/src/types/responseData.ts
  client/src/utils/map/naverMap.ts
Labels: 🎨 FE, 🐞 BugFix, 🛠 Feat, 🚧 Refactor

#143 [fe/map update] 지도 영역 변경시 timeout 이후 데이터 요청 및 지도 페이지 리팩토링
  client/src/constants/map.ts
  client/src/hooks/useCurrentLocation.ts
  client/src/pages/MapPage/MapPage.tsx
  client/src/pages/NewPostPage/NewPostPage.tsx
  client/src/utils/map/naverMap.ts
Labels: 🎨 FE, 🛠 Feat, 🚧 Refactor

#144 [fe/map update] 모바일 버그 수정
  client/src/components/SetLocationModal/SetLocationModalStyles.tsx
  client/src/pages/NewPostPage/NewPostPage.tsx
  client/src/utils/map/naverMap.ts
Labels: 🎨 FE, 🐞 BugFix

#147 [fe/fix home] 게시글 관련 버그 수정
  client/src/App.tsx
  client/src/components/SetLocationModal/SetLocationModalStyles.tsx
  client/src/index.css
  client/src/pages/HomePage/HomePage.tsx
  client/src/pages/MapPage/MapPageStyles.tsx
Labels: 🎨 FE, 🐞 BugFix

#146 [fe/refactor code] 전반적인 코드 리팩토링 및 gzip 설정
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/apis/api/loginApi.ts
  client/src/apis/api/userApi.ts
  client/src/components/CommentUnit/CommentUnit.tsx
  client/src/components/ErrorBoundary/ErrorBoundary.tsx
  client/src/components/LoadingContainer/LoadingContainer.tsx
  client/src/components/MessageBox/MessageForm.tsx
  client/src/components/MessageBox/MessageFormStyles.tsx
  client/src/components/NavBar/NavBar.tsx
  client/src/components/ProfileIcon/ProfileIcon.tsx
  client/src/components/UserInfoContainer/UserInfoContainer.tsx
  client/src/components/UserPostContainer/UserPostContainer.tsx
  client/src/hooks/useNickname.ts
  client/src/pages/CommentPage/CommentPage.tsx
  client/src/pages/HomePage/HomePage.tsx
  client/src/pages/LoadingPage/LoadingPage.tsx
  client/src/pages/LoginPage/LoginPage.tsx
  client/src/pages/LoginPage/LoginPageStyles.tsx
  client/src/pages/ModifyUserPage/ModifyUserPage.tsx
  client/src/pages/RegisterPage/RegisterPage.tsx
  client/src/pages/RegisterPage/RegisterPageStyles.tsx
  client/src/pages/UserPage/UserPage.tsx
  client/src/store/userAtom.ts
  client/src/types/responseData.ts
  client/src/utils/loginUtils.ts
  environment/default.conf
  server/src/auth/auth.service.ts
Labels: 🎨 FE, 🚧 Refactor

#148 [fe/fix_home] Revert "fix: 좋아요 클릭시, stale한 board 데이터 업데이트"
  client/src/pages/HomePage/HomePage.tsx
Labels: 🎨 FE, 🐞 BugFix

#150 [fe/refactor code] github oauth 로그인 기능 추가
  client/src/App.tsx
  client/src/apis/api/loginApi.ts
  client/src/pages/LoadingPage/LoadingPage.tsx
  client/src/pages/LoginPage/LoginPage.tsx
  client/src/pages/LoginPage/LoginPageStyles.tsx
  client/src/pages/RegisterPage/RegisterPage.tsx
  client/src/static/githubOauth.png
  client/src/utils/loginUtils.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/oauth-github.dto.ts
  server/src/auth/model/oauth-info.enum.ts
Labels: 🎨 FE, 💻 BE, 🛠 Feat, 🚧 Refactor

#145 [be/refactor] 사용자 이름 validate, 개인정보 수정 api 리팩토링, 모듈 구조 리팩토링, authGuard 및 responseInterceptor 리팩토링
  client/src/apis/api/loginApi.ts
  client/src/hooks/useNickname.ts
  client/src/pages/LoadingPage/LoadingPage.tsx
  client/src/pages/ModifyUserPage/ModifyUserPage.tsx
  client/src/pages/RegisterPage/RegisterPage.tsx
  client/src/types/responseData.ts
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.guard.ts
  server/src/auth/auth.service.spec.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/check-name.dto.ts
  server/src/board/board.controller.ts
  server/src/board/board.entity.ts
  server/src/board/board.repository.ts
  server/src/board/board.service.ts
  server/src/board/board.util.ts
  server/src/comment/comment.entity.ts
  server/src/comment/comment.service.ts
  server/src/configs/typeorm.config.ts
  server/src/interceptor/responseInterceptor.ts
  server/src/like/like.entity.ts
  server/src/main.ts
  server/src/redis/redis.module.ts
  server/src/redis/redis.ts
  server/src/redis/redisProvider.ts
  server/src/user/dto/create-user.dto.ts
  server/src/user/dto/update-user-info.dto.ts
  server/src/user/dto/validate-name.dto.ts
  server/src/user/follow/follow.entity.ts
  server/src/user/user.controller.ts
  server/src/user/user.entity.ts
  server/src/user/user.module.ts
  server/src/user/user.repository.ts
  server/src/user/user.service.spec.ts
  server/src/user/user.service.ts
  server/test/app.e2e-spec.ts
Labels: 🎨 FE, 💻 BE, 🐞 BugFix, 🚧 Refactor

#151 [fe/refactor code] 회원정보 수정시 오류와 홈화면 무한스크롤 임시 적용
  client/package-lock.json
  client/package.json
  client/src/apis/api/userApi.ts
  client/src/components/BoardItem/BoardItem.tsx
  client/src/components/UserInfoContainer/UserInfoContainer.tsx
  client/src/components/UserPostContainer/UserPostContainerStyles.tsx
  client/src/hooks/useNickname.ts
  client/src/pages/HomePage/HomePage.tsx
  client/src/pages/ModifyUserPage/ModifyUserPage.tsx
  client/src/store/userProfileAtom.ts
  client/src/types/responseData.ts
Labels: 🎨 FE, 🛠 Feat, 🚧 Refactor

#153 fix: infinite query로 변경하며 바뀐 게시글 데이터의 key 적용
  client/src/components/LikeButton/LikeButton.tsx
Labels: 🎨 FE, 🐞 BugFix

#155 [be/pm2 cluster] pm2 클러스터링 도입, 성능개선
  .github/workflows/cd.yml
  server/Dockerfile
  server/package-lock.json
  server/package.json
  server/pm2.config.js
  server/src/auth/auth.guard.ts
  server/src/auth/auth.service.ts
  server/src/main.ts
  server/src/redis/redisProvider.ts
Labels: 💻 BE, 🌏 CI/CD, 🚧 Refactor, ⚡Enhanced

#156 [be/bugfix] Interceptor 적용으로 인한 오류 해결
  server/src/board/board.repository.ts
  server/src/comment/comment.repository.ts
  server/src/map/map.controller.ts
Labels: 💻 BE, 🐞 BugFix

#157 Fe/refactoring 1214
  client/src/components/BoardItem/BoardBody/BoardBody.tsx
  client/src/components/BoardItem/BoardBody/BoardBodyStyles.tsx
  client/src/components/FollowContainer/FollowContainerStyles.tsx
  client/src/components/MessageBox/MessageFormStyles.tsx
  client/src/components/UserInfoContainer/UserInfoContainerStyles.tsx
  client/src/pages/BoardDetailPage/BoardDetailPageStyles.tsx
  client/src/pages/CommentPage/CommentPageStyles.tsx
  client/src/pages/HomePage/HomePageStyles.tsx
  client/src/pages/MapPage/MapPageStyles.tsx
  server/src/board/board.util.ts
Labels: 🎨 FE, 💻 BE, 🐞 BugFix

#159 [fe/DmListPage] DmListPage UI 구조 생성
  client/src/App.tsx
  client/src/components/DmListContainer/DmListContainer.tsx
  client/src/components/DmListContainer/DmListContainerStyles.tsx
  client/src/components/DmListUnit/DmListUnit.tsx
  client/src/components/DmListUnit/DmListUnitStyles.tsx
  client/src/index.css
  client/src/pages/DmListPage/DmListPage.tsx
  client/src/pages/index.tsx
Labels: 🎨 FE, 🛠 Feat

#161 [fe/fix-mobile-style] 모바일 환경에서 버튼 구조 변경
  client/src/components/ProfileIcon/ProfileIcon.tsx
  client/src/components/UserInfoContainer/UserInfoContainerStyles.tsx
  client/src/pages/LoginPage/LoginPageStyles.tsx
Labels: 🎨 FE, 🚧 Refactor

#163 [fe/fix-mobile-style] 모바일 환경에서 버튼 구조 변경
  client/src/components/UserInfoContainer/UserInfoContainerStyles.tsx
Labels: 🎨 FE, 🚧 Refactor

#164 [fe/fix-mobile-style] webkit 속성으로 인한 변경 제거
  client/src/index.css
Labels: 🎨 FE, 🚧 Refactor

#166 [fe/direct message page] DM 기능 UI 및 API 작성
  client/src/App.tsx
  client/src/apis/api/dmApi.ts
  client/src/components/BoardItem/BoardHeader/BoardHeader.tsx
  client/src/components/BoardItem/BoardHeader/BoardHeaderStyles.tsx
  client/src/components/DirectMessage/DirectMessage.tsx
  client/src/components/DirectMessage/DirectMessageStyles.tsx
  client/src/components/FollowUnit/FollowUnit.tsx
  client/src/pages/DirectMessagePage/DirectMessagePage.tsx
  client/src/pages/DirectMessagePage/DirectMessagePageStyles.tsx
  client/src/pages/index.tsx
  client/src/types/responseData.ts
Labels: 🎨 FE, 🐞 BugFix, 🛠 Feat

#168 [chat] chat -> dm 이름 변경
  client/src/socket/socket.ts
  server/api/src/dm/dm.module.ts
  server/api/src/dm/dm.service.ts
  server/api/src/dm/dmroom.entity.ts
  server/api/src/dm/dmroom.repository.ts
  server/dao/repository/dm.repository.ts
  server/dao/schemas/dm.schema.ts
  socket/src/main.ts
  socket/test/jest-e2e.json
Labels: ⚙️ Settings
