Repository boostcampwm-2022/web09-KittyMark, pull requests merged in 2022-11, with the labels that each got.

#16 [hotfix/eslint_config] client eslint config 수정
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
Labels: 🔥 Hotfix

#17 [fe/login/UI] login 과 register 기본 UI 생성
  client/src/@types/images.d.ts
  client/src/App.css
  client/src/App.tsx
  client/src/components/NormalTopBar/NormalTopBar.tsx
  client/src/fonts/BMJUA_ttf.ttf
  client/src/index.css
  client/src/index.tsx
  client/src/pages/HomePage/HomePage.tsx
  client/src/pages/RegisterPage/RegisterPage.tsx
  client/src/pages/RegisterPage/RegisterPageStyles.tsx
  client/src/pages/StartPage/StartPage.tsx
  client/src/pages/StartPage/StartPageStyles.tsx
  client/src/static/defaultProfile.svg
  client/src/static/kakao_oauth.png
  client/src/static/logo.png
  client/src/static/logoName.png
  client/src/static/naver_oauth.png
  client/src/static/plusBtn.svg
Labels: 🎨 FE

#19 [fe/register] 버튼 및 입력 이벤트 생성, favicon 설정
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/src/logo.svg
  client/src/pages/RegisterPage/RegisterPage.tsx
  client/src/pages/RegisterPage/RegisterPageStyles.tsx
Labels: 🎨 FE, 🛠 Feat

#21 [hotfix/github_action_build_error] eslint 에러 요소 제거
  client/src/pages/HomePage/HomePage.tsx
  client/src/pages/RegisterPage/RegisterPage.tsx
Labels: 🔥 Hotfix

#23 [ci/cd] docker 설정 및 github action 스크립트 작성
  .github/workflows/deploy.yml
  client/Dockerfile
  client/default.conf
  docker-compose-build.yml
  docker-compose.yml
  nginx/Dockerfile
  nginx/default.conf
  server/Dockerfile
  server/src/main.ts
Labels: 💻 BE, 🌏 CI/CD, ⚙️ Settings

#22 [fe/login] 네이버 로그인 authorization code 요청
  client/.gitignore
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/pages/LoginPage/LoginPage.tsx
  client/src/pages/LoginPage/LoginPageStyles.tsx
  client/src/pages/StartPage/StartPage.tsx
  client/src/setupProxy.js
  server/0001-init-server-nest.js.patch
Labels: 🎨 FE, 🛠 Feat

#24 [fe/login_loading] 로그인 로딩 페이지 생성
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/index.css
  client/src/pages/LoadingPage/LoadingPage.tsx
  client/src/pages/LoadingPage/LoadingPageStyles.tsx
  client/src/pages/LoginPage/LoginPage.tsx
  client/src/reportWebVitals.ts
  client/src/setupProxy.js
  client/src/static/loadingCat.gif
Labels: 🎨 FE, 🛠 Feat

#25 [fe/register] 회원가입 페이지 이미지 저장 및 api 요청 처리 완료
  client/package-lock.json
  client/package.json
  client/public/defaultProfile.svg
  client/src/components/NavBar/NavBar.tsx
  client/src/components/NavBar/NavBarStyles.tsx
  client/src/components/NormalTopBar/NormalTopBar.tsx
  client/src/pages/HomePage/HomePage.tsx
  client/src/pages/LoadingPage/LoadingPage.tsx
  client/src/pages/RegisterPage/RegisterPage.tsx
  client/src/static/homeIcon.svg
  client/src/static/mapIcon.svg
  client/src/static/messageIcon.svg
  client/src/static/tempHomeBody.png
  client/src/static/userIcon.svg
  client/src/utils/awsUpload.ts
Labels: 🎨 FE, 🛠 Feat

#26 [fe/register] typescript interface 설정 및 적용
  client/package-lock.json
  client/package.json
  client/src/pages/LoadingPage/LoadingPage.tsx
  client/src/pages/RegisterPage/RegisterPage.tsx
  client/src/pages/RegisterPage/RegisterPageStyles.tsx
  client/src/types/images.d.ts
  client/src/types/responseData.ts
Labels: 🎨 FE, 🚧 Refactor

#27 [ci] PR시 build 테스트
  .github/workflows/ci.yml
Labels: 💻 BE, 🌏 CI/CD, ⚙️ Settings

#29 [fe/refactor style] themeProvider 를 통한 스타일 부여
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/components/NavBar/NavBarStyles.tsx
  client/src/components/NormalTopBar/NormalTopBar.tsx
  client/src/pages/HomePage/HomePage.tsx
  client/src/pages/LoadingPage/LoadingPage.tsx
  client/src/pages/LoadingPage/LoadingPageStyles.tsx
  client/src/pages/LoginPage/LoginPageStyles.tsx
  client/src/pages/RegisterPage/RegisterPage.tsx
  client/src/pages/RegisterPage/RegisterPageStyles.tsx
Labels: 🎨 FE, 🚧 Refactor

#32 [fe/refactor_apis] api 로직 분리
  client/src/apis/api/loginApi.ts
  client/src/apis/config.ts
  client/src/apis/utils/index.ts
  client/src/pages/LoadingPage/LoadingPage.tsx
  client/src/pages/RegisterPage/RegisterPage.tsx
Labels: 🎨 FE, 🚧 Refactor

#33 [ci-style] 코드 스타일 적용 및 테스트 추가
  .github/workflows/ci.yml
  client/.eslintrc.js
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/apis/api/loginApi.ts
  client/src/apis/utils/index.ts
  client/src/components/NavBar/NavBar.tsx
  client/src/components/NavBar/NavBarStyles.tsx
  client/src/components/NormalTopBar/NormalTopBar.tsx
  client/src/index.tsx
  client/src/pages/HomePage/HomePage.tsx
  client/src/pages/LoadingPage/LoadingPage.tsx
  client/src/pages/LoadingPage/LoadingPageStyles.tsx
  client/src/pages/LoginPage/LoginPage.tsx
  client/src/pages/LoginPage/LoginPageStyles.tsx
  client/src/pages/RegisterPage/RegisterPage.tsx
  client/src/pages/RegisterPage/RegisterPageStyles.tsx
  client/src/reportWebVitals.ts
  client/src/setupProxy.js
  client/src/types/responseData.ts
  client/src/utils/awsUpload.ts
  server/.development.env
  server/.eslintrc.js
  server/.gitignore
  server/.prettierrc
  server/.production.env
  server/package-lock.json
  server/package.json
  server/src/app.controller.spec.ts
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/auth/auth.controller.spec.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.dto.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.spec.ts
  server/src/auth/auth.service.ts
  server/src/database/database.module.ts
  server/src/database/database.provider.ts
  server/src/main.ts
  server/src/oauth/oauth-naver.dto.ts
  server/src/oauth/oauth.controller.spec.ts
  server/src/oauth/oauth.controller.ts
  server/src/oauth/oauth.module.ts
  server/src/oauth/oauth.service.spec.ts
  server/src/oauth/oauth.service.ts
  server/src/user/user-register.dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.entity.ts
  server/src/user/user.module.ts
  server/src/user/user.providers.ts
  server/src/user/user.service.ts
  server/src/user/user.spec.ts
  server/test/app.e2e-spec.ts
Labels: 🎨 FE, 💻 BE, 🌏 CI/CD, ⚙️ Settings, 🛠 Feat

#57 [be/bugfix pending login] 로그인 요청시 대기 상태 문제
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/cache/cache.module.ts
  server/src/cache/cache.provider.ts
  server/src/database/database.provider.ts
  server/src/main.ts
  server/src/redis.ts
Labels: 💻 BE, 🐞 BugFix

#58 [be/test] user register 테스트 코드 작성
  client/src/apis/api/loginApi.ts
  server/src/auth/auth.service.ts
  server/src/user/user-register.dto.ts
  server/src/user/user.entity.ts
  server/src/user/user.enum.ts
  server/src/user/user.service.spec.ts
  server/src/user/user.service.ts
  server/src/user/user.spec.ts
Labels: 🎨 FE, 💻 BE, 🐞 BugFix

#60 [ci-test] CD 수정 테스트
  .github/workflows/deploy.yml
  server/.gitignore
  server/src/app.controller.spec.ts
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/app.service.ts
  server/src/main.ts
Labels: 🌏 CI/CD, ⚙️ Settings

#62 [be/refactor] 모듈 구조 및 TypeORM 연결 방식 변경
  client/src/apis/api/loginApi.ts
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.dto.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.spec.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/oauth-naver.dto.ts
  server/src/auth/dto/user-register.dto.ts
  server/src/auth/model/oauth-info.enum.ts
  server/src/configs/typeorm.config.ts
  server/src/database/database.module.ts
  server/src/database/database.provider.ts
  server/src/oauth/oauth.controller.spec.ts
  server/src/oauth/oauth.controller.ts
  server/src/oauth/oauth.module.ts
  server/src/oauth/oauth.service.spec.ts
  server/src/oauth/oauth.service.ts
  server/src/user/user-register.dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.entity.ts
  server/src/user/user.module.ts
  server/src/user/user.providers.ts
  server/src/user/user.repository.ts
  server/src/user/user.service.ts
  server/src/utils/redis.ts
  test.js
Labels: 🎨 FE, 💻 BE, 🐞 BugFix, 🚧 Refactor

#61 [cd/server-env] 배포서버에 서버 env 파일 추가
  .github/workflows/deploy.yml
  server/.gitignore
  server/src/main.ts
Labels: 💻 BE, 🐞 BugFix, 🌏 CI/CD

#59 [fe/comment] 댓글 페이지 기본 UI 및 api 통신 연결
  client/src/App.tsx
  client/src/apis/api/commentApi.ts
  client/src/apis/api/loginApi.ts
  client/src/apis/utils/index.ts
  client/src/components/CommentUnit/CommentUnit.tsx
  client/src/components/CommentUnit/CommentUnitStyles.tsx
  client/src/components/MessageBox/MessageForm.tsx
  client/src/components/MessageBox/MessageFormStyles.tsx
  client/src/components/ProfileIcon/ProfileIcon.tsx
  client/src/components/TopBar/TopBar.tsx
  client/src/components/TopBar/TopBarStyles.tsx
  client/src/pages/CommentPage/CommentPage.tsx
  client/src/pages/CommentPage/CommentPageStyles.tsx
  client/src/pages/RegisterPage/RegisterPage.tsx
  client/src/static/backBtn.svg
  client/src/static/checkBtn.svg
  client/src/static/menuBtn.svg
  client/src/static/sendBtn.svg
  client/src/store/userAtom.ts
  client/src/types/responseData.ts
Labels: 🎨 FE, 🛠 Feat

#63 [be/board-crud] 게시판 작성, 수정 추가
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/board/board.controller.spec.ts
  server/src/board/board.controller.ts
  server/src/board/board.entity.ts
  server/src/board/board.module.ts
  server/src/board/board.repository.ts
  server/src/board/board.service.spec.ts
  server/src/board/board.service.ts
  server/src/board/dto/createBoardDto.ts
  server/src/board/dto/deleteBoardDto.ts
  server/src/board/dto/likeBoardDto.ts
  server/src/board/dto/updateBoaedDto.ts
  server/src/board/photo.entity.ts
  server/src/configs/typeorm.config.ts
  server/src/interceptor/responseInterceptor.ts
  server/src/user/user.entity.ts
  server/src/user/user.repository.ts
  server/tsconfig.json
Labels: 💻 BE, 🛠 Feat

#64 [fe/new post] 게시글 추가 화면 생성 및 이벤트, API 연결
  client/src/App.tsx
  client/src/apis/api/newPostApi.ts
  client/src/components/ImageSlot/ImageSlot.tsx
  client/src/components/ImageSlot/ImageSlotStyles.tsx
  client/src/components/TopBar/TopBar.tsx
  client/src/components/TopBar/TopBarStyles.tsx
  client/src/pages/NewPostPage/NewPostPage.tsx
  client/src/pages/NewPostPage/NewPostPageStyles.tsx
  client/src/static/addImgIcon.svg
  client/src/static/delBtn.svg
  client/src/static/locationIcon.svg
  client/src/types/responseData.ts
Labels: 🎨 FE, 🛠 Feat

#66 [be/get-boardlist] 게시글을 n개씩 불러온다
  server/src/board/board.controller.ts
  server/src/board/board.entity.ts
  server/src/board/board.module.ts
  server/src/board/board.repository.ts
  server/src/board/board.service.ts
  server/src/board/dto/createBoardDto.ts
  server/src/board/photo.repository.ts
  server/src/user/user.entity.ts
  server/src/user/user.repository.ts
Labels: 💻 BE, 🛠 Feat

#67 [ be/common] 오브젝트 스토리지 이미지 저장 & 별명 중복 체크 기능 구현
  server/package-lock.json
  server/package.json
  server/src/S3/S3.module.ts
  server/src/S3/s3.service.spec.ts
  server/src/S3/s3.service.ts
  server/src/app.module.ts
  server/src/user/dto/check-name.dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.repository.ts
  server/src/user/user.service.ts
Labels: 💻 BE, 🛠 Feat

#68 [fe/refactor_api] api 명세 변경에 따른 코드 수정
  client/src/apis/api/BoardApi.ts
  client/src/apis/api/commentApi.ts
  client/src/apis/api/loginApi.ts
  client/src/apis/api/newPostApi.ts
  client/src/apis/config.ts
  client/src/pages/CommentPage/CommentPage.tsx
  client/src/pages/LoadingPage/LoadingPage.tsx
  client/src/pages/NewPostPage/NewPostPage.tsx
  client/src/pages/RegisterPage/RegisterPage.tsx
  client/src/types/responseData.ts
Labels: 🎨 FE, 🚧 Refactor

#69 [be/refactor] plainToInstance 사용 및 statusCode 속성 변경
  server/src/auth/auth.service.ts
  server/src/auth/dto/user-register.dto.ts
  server/src/user/user.repository.ts
Labels: 💻 BE, 🚧 Refactor

#71 [fe/connect home api] 홈 화면에서 페이지 라우팅 추가 및 API 연결
  client/src/apis/api/BoardApi.ts
  client/src/components/BoardItem/BoardBody/BoardBody.tsx
  client/src/components/BoardItem/BoardHeader/BoardHeader.tsx
  client/src/components/BoardItem/BoardImages/BoardImages.tsx
  client/src/components/BoardItem/BoardItem.tsx
  client/src/components/BoardItem/BoardMenu/BoardMenu.tsx
  client/src/components/NormalTopBar/NormalTopBar.tsx
  client/src/pages/HomePage/HomePage.tsx
  client/src/pages/RegisterPage/RegisterPage.tsx
  client/src/static/addPost.svg
  client/src/types/responseData.ts
Labels: 🎨 FE, 🛠 Feat

#74 [bug/deploy-error] 배포 에러 수정
  client/default.conf
Labels: 🐞 BugFix, 🌏 CI/CD, ⚙️ Settings

#70 [be/authrozation] 로그인 인가
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/auth/auth.guard.ts
  server/src/auth/auth.service.ts
  server/src/board/board.controller.ts
  server/src/main.ts
Labels: 💻 BE, 🛠 Feat

#73 [be/comment] 댓글 엔티티 모듈 및 등록, 조회 API 구현
  server/src/board/board.entity.ts
  server/src/comment/comment.controller.spec.ts
  server/src/comment/comment.controller.ts
  server/src/comment/comment.entity.ts
  server/src/comment/comment.module.ts
  server/src/comment/comment.repository.ts
  server/src/comment/comment.service.spec.ts
  server/src/comment/comment.service.ts
  server/src/comment/dto/create-comment.dto.ts
  server/src/comment/dto/get-comments.dto.ts
  server/src/configs/typeorm.config.ts
  server/src/user/user.entity.ts
Labels: 💻 BE, 🛠 Feat

#72 [be/refactor] 유저 등록 시 request 데이터 multipart/form type으로 처리
  server/src/S3/S3.module.ts
  server/src/S3/S3.service.spec.ts
  server/src/S3/S3.service.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/user-register.dto.ts
Labels: 💻 BE, 🚧 Refactor

#76 [be/deploy-bugfix] 배포시 버그 수정
  client/src/apis/api/BoardApi.ts
  client/src/apis/api/commentApi.ts
  client/src/apis/api/loginApi.ts
  client/src/apis/api/newPostApi.ts
  client/src/components/BoardItem/BoardBody/BoardBodyStyles.tsx
  client/src/components/BoardItem/BoardHeader/BoardHeader.tsx
  client/src/components/BoardItem/BoardHeader/BoardHeaderStyles.tsx
  client/src/components/BoardItem/BoardItem.tsx
  client/src/pages/CommentPage/CommentPage.tsx
  client/src/pages/HomePage/HomePage.tsx
  client/src/pages/LoadingPage/LoadingPage.tsx
  client/src/store/userAtom.ts
  client/src/types/responseData.ts
  server/src/S3/S3.service.ts
  server/src/app.module.ts
  server/src/auth/auth.service.ts
  server/src/board/board.controller.ts
  server/src/board/board.entity.ts
  server/src/board/board.repository.ts
  server/src/board/board.service.ts
  server/src/board/dto/createBoardDto.ts
  server/src/comment/comment.controller.ts
  server/src/comment/comment.entity.ts
  server/src/comment/comment.repository.ts
  server/src/configs/typeorm.config.ts
Labels: 🎨 FE, 💻 BE, 🐞 BugFix, 🌏 CI/CD

#77 [fe/refactor hook] 스타일 코드 변경 및 custom hook 적용
  client/src/apis/api/loginApi.ts
  client/src/components/ImageSlot/ImageSlot.tsx
  client/src/components/ImageSlot/ImageSlotStyles.tsx
  client/src/components/NavBar/NavBar.tsx
  client/src/components/NavBar/NavBarStyles.tsx
  client/src/components/NormalTopBar/NormalTopBar.tsx
  client/src/components/TopBar/TopBar.tsx
  client/src/components/TopBar/TopBarStyles.tsx
  client/src/hooks/useImage.ts
  client/src/hooks/useImages.ts
  client/src/hooks/useInputs.ts
  client/src/pages/CommentPage/CommentPage.tsx
  client/src/pages/CommentPage/CommentPageStyles.tsx
  client/src/pages/LoadingPage/LoadingPage.tsx
  client/src/pages/LoadingPage/LoadingPageStyles.tsx
  client/src/pages/LoginPage/LoginPage.tsx
  client/src/pages/LoginPage/LoginPageStyles.tsx
  client/src/pages/NewPostPage/NewPostPage.tsx
  client/src/pages/NewPostPage/NewPostPageStyles.tsx
  client/src/pages/RegisterPage/RegisterPage.tsx
  client/src/pages/RegisterPage/RegisterPageStyles.tsx
  client/src/types/imageData.ts
  client/src/types/responseData.ts
Labels: 🎨 FE, 🚧 Refactor

#97 [fe/comment] 댓글 수정 삭제 기능 추가
  client/src/App.tsx
  client/src/apis/api/commentApi.ts
  client/src/components/CommentUnit/CommentUnit.tsx
  client/src/components/MenuModal/MenuModal.tsx
  client/src/pages/CommentPage/CommentPage.tsx
  client/src/pages/ModifyPage/ModifyPage.tsx
  client/src/pages/ModifyPage/ModifyPageStyles.tsx
Labels: 🎨 FE, 🛠 Feat

#99 [fe/register] 중복 체크 버튼 생성 및 로직 연결
  client/src/apis/api/loginApi.ts
  client/src/pages/RegisterPage/RegisterPage.tsx
  client/src/pages/RegisterPage/RegisterPageStyles.tsx
  client/src/types/responseData.ts
Labels: 🎨 FE, 🛠 Feat

#100 [fe/board bugfix] 게시글 관련 버그 수정, 메뉴 모달 적용, 게시글 수정
  client/src/apis/api/boardApi.ts
  client/src/components/BoardItem/BoardHeader/BoardHeader.tsx
  client/src/components/BoardItem/BoardItem.tsx
  client/src/components/BoardItem/BoardMenu/BoardMenu.tsx
  client/src/components/MenuModal/MenuModalStyles.tsx
  client/src/pages/HomePage/HomePage.tsx
Labels: 🎨 FE, 🐞 BugFix, 🛠 Feat, 🚧 Refactor

#101 [fe/home img carousel] 캐러셀로 게시글 이미지 보여주기
  client/package-lock.json
  client/package.json
  client/src/components/BoardItem/BoardHeader/BoardHeader.tsx
  client/src/components/BoardItem/BoardImages/BoardImages.tsx
  client/src/components/BoardItem/BoardImages/BoardImagesStyles.tsx
  client/src/components/BoardItem/BoardItem.tsx
  client/src/components/BoardItem/BoardItemStyles.tsx
  client/src/components/ImageCarousel/CarouselItem/CarouselItem.tsx
  client/src/components/ImageCarousel/ImageCarousel.tsx
Labels: 🎨 FE, 🐞 BugFix, 🛠 Feat

#103 [be/https] 경로수정
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 CI/CD

#104 [be/https] 경로변경 적용
  .github/workflows/deploy.yml
  environment/docker-compose-build.yml
Labels: 🐞 BugFix, 🌏 CI/CD

#105 [dev] 깃헙액션 cd수정
  .github/workflows/cd.yml
  environment/docker-compose.yml
Labels: 🐞 BugFix, 🌏 CI/CD, ⚙️ Settings

#107 [fe/user page] 개인 페이지 상단 및 팔로우 페이지 디자인 및 api 연결
  client/src/App.tsx
  client/src/apis/api/userApi.ts
  client/src/components/CommentUnit/CommentUnit.tsx
  client/src/components/FollowUnit/FollowUnit.tsx
  client/src/components/FollowerContainer/FollowerContainerPage.tsx
  client/src/components/FollowerContainer/FollowerContainerStyles.tsx
  client/src/components/FollowingContainer/FollowingContainer.tsx
  client/src/components/FollowingContainer/FollowingContainerStyles.tsx
  client/src/components/MessageBox/MessageForm.tsx
  client/src/components/NavBar/NavBar.tsx
  client/src/components/ProfileIcon/ProfileIcon.tsx
  client/src/components/UserInfoContainer/UserInfoContainer.tsx
  client/src/components/UserInfoContainer/UserInfoContainerStyles.tsx
  client/src/components/UserPostContainer/UserPostContainer.tsx
  client/src/components/UserPostContainer/UserPostContainerStyles.tsx
  client/src/pages/CommentPage/CommentPage.tsx
  client/src/pages/FollowPage/FollowPage.tsx
  client/src/pages/FollowPage/FollowerPageStyles.tsx
  client/src/pages/LoadingPage/LoadingPage.tsx
  client/src/pages/RegisterPage/RegisterPage.tsx
  client/src/pages/UserPage/UserPage.tsx
  client/src/pages/UserPage/UserPageStyles.tsx
  client/src/store/userAtom.ts
  client/src/types/responseData.ts
  client/src/utils/awsUpload.ts
  client/src/utils/timeCalc.ts
Labels: 🎨 FE, 🛠 Feat, 🚧 Refactor

#109 [be/user] 개인페이지 API 작성
  server/src/board/board.controller.ts
  server/src/board/board.repository.ts
  server/src/board/board.service.ts
  server/src/board/dto/get-user-boards.dto.ts
  server/src/user/dto/get-profile-info.dto.ts
  server/src/user/dto/update-user-info.dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.repository.ts
  server/src/user/user.service.ts
Labels: 💻 BE, 🛠 Feat

#108 [fe/map] 지도 페이지 구현
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/apis/api/mapApi.ts
  client/src/components/NavBar/NavBar.tsx
  client/src/pages/MapPage/MapPage.tsx
  client/src/pages/MapPage/MapPageStyles.tsx
  client/src/static/loadingCat.gif
  client/src/static/tempHomeBody.png
  client/src/types/responseData.ts
  client/src/utils/map.ts
Labels: 🎨 FE, 🛠 Feat, 🚧 Refactor
