Repository boostcampwm-2022/web09-KittyMark, pull requests merged in 2023-01, with the labels that each got.

#169 [fe/DmListPage] DM 리스트 페이지 api 연결 처리
  client/src/App.tsx
  client/src/apis/api/dmApi.ts
  client/src/components/BoardItem/BoardHeader/BoardHeader.tsx
  client/src/components/BoardItem/BoardHeader/BoardHeaderStyles.tsx
  client/src/components/DirectMessage/DirectMessage.tsx
  client/src/components/DirectMessage/DirectMessageStyles.tsx
  client/src/components/DmListContainer/DmListContainer.tsx
  client/src/components/DmListUnit/DmListUnit.tsx
  client/src/components/FollowUnit/FollowUnit.tsx
  client/src/pages/DirectMessagePage/DirectMessagePage.tsx
  client/src/pages/DirectMessagePage/DirectMessagePageStyles.tsx
  client/src/pages/index.tsx
  client/src/types/responseData.ts
Labels: 🎨 FE, 🛠 Feat

#170 [be/dm] DM 관련 api 작성
  server/.eslintrc.js
  server/api/src/app.module.ts
  server/api/src/configs/typeorm.config.ts
  server/api/src/dm/dm.controller.ts
  server/api/src/dm/dm.service.ts
  server/api/src/dm/dmroom.entity.ts
  server/api/src/dm/dmroom.repository.ts
  server/api/src/dm/dto/get-message.dto.ts
  server/api/src/dm/dto/update-lastSeenChat.dto.ts
  server/api/src/main.ts
  server/api/test/app.e2e-spec.ts
  server/dao/repository/dm.repository.ts
  server/package.json
Labels: 💻 BE, 🛠 Feat

#174 [be/dm socket] DM 소켓 이벤트 작성
  server/dao/repository/dm.repository.ts
  server/dao/schemas/dm.schema.ts
  server/package-lock.json
  server/package.json
  server/socket/Dockerfile
  server/socket/src/event/dmEvent.interface.ts
  server/socket/src/event/dmEvent.service.ts
  server/socket/src/event/event.gateway.ts
  server/socket/src/event/event.module.ts
  server/socket/src/main.ts
  server/socket/src/redis.adapter.ts
Labels: 💻 BE, 🛠 Feat

#175 [fe/refactor code] 로그인, 로딩, 홈 페이지 리팩토링
  client/package-lock.json
  client/package.json
  client/src/components/LoadingContainer/LoadingContainer.tsx
  client/src/hooks/useBoardQuery.ts
  client/src/hooks/useLoginCheck.ts
  client/src/hooks/usePostAuthInfo.ts
  client/src/hooks/useUnauthor.ts
  client/src/pages/HomePage/HomePage.tsx
  client/src/pages/LoadingPage/LoadingPage.tsx
  client/src/pages/LoginPage/LoginPage.tsx
  client/src/socket/socket.ts
Labels: 🎨 FE, 🚧 Refactor

#176 [docker-setting] CI/CD 설정 변경
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  environment/default.conf
  environment/docker-compose-build.yml
  environment/docker-compose.yml
  server/api/.dockerignore
  server/api/Dockerfile
  server/apiDockerfile
  server/package.json
  server/pm2.config.js
  server/socket/Dockerfile
  server/socketDockerfile
Labels: 💻 BE, 🌏 CI/CD, ⚙️ Settings

#177 [fe/refactor code] 소켓 부분 코드 컨텍스트로 분리
  client/src/App.tsx
  client/src/pages/DirectMessagePage/DirectMessagePage.tsx
  client/src/store/SocketContext.ts
Labels: 🎨 FE, 🚧 Refactor

#180 [proxy] 로컬, 배포 프록시 설정 변경
  client/src/setupProxy.js
  environment/default.conf
Labels: 🎨 FE, 🐞 BugFix, ⚙️ Settings

#179 [Be/dm] updatelastSeenDM 버그 수정 및 DM Schema에 toClient() 메소드 추가
  server/api/src/dm/dm.controller.ts
  server/api/src/dm/dm.service.ts
  server/dao/repository/dm.repository.ts
  server/dao/schemas/dm.schema.ts
  server/package-lock.json
  server/package.json
Labels: 💻 BE, 🐞 BugFix, 🚧 Refactor
